name: Tests

on:
  pull_request:
    branches: 
    - 'release/**'
    - 'master'
    - 'develop'
    - 'release-app_**'
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DVELOPMENT_ANDROID }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Bundle Install
      run: bundle install
    - name: Tests
      run: |
        echo sdk.dir = $ANDROID_HOME > local.properties
        bundle exec fastlane test
    - name: Build notification
      if: failure()
      uses: adamkdean/simple-slack-notify@master
      with:
        channel: '#development-android'
        text: 'Neutral build #${{ github.run_number }} failed'
        color: 'danger'
        fields: |
          [{ "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"}]
